### ISSUE TITLE
token parameter not in video issue

### ISSUE THREAD

**Issue by carlosperate** [jaimeMF/youtube-dl-web#17] opened 2017-04-20 15:00 UTC
Hi,

No matter which youtube video I try (including the example one) I always get the following response from https://youtube-dl.appspot.com/api/info:
```
{
  "error": "ERROR: xxx: \"token\" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."
}
```

Could it be that the version of youtube-dl in that server needs updating?

**Comment by jaimeMF** [comment] 2017-05-01 12:44
Duplicate of https://github.com/jaimeMF/youtube-dl-api-server/issues/55

**Closed as completed by jaimeMF** 2017-05-01 12:44 UTC
